# Generated by Django 5.2.7 on 2025-10-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('image', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
